### ISSUE TITLE
error install backpack:base

### ISSUE THREAD

**Issue by kuteteen** [iMokhles/IMRepo#1]
1/8 [▓▓▓░░░░░░░░░░░░░░░░░░░░░░░░░]  12% Installing backpack/generators

   Symfony\Component\Process\Exception\ProcessSignaledException  : The process has been signaled with signal "9".

help me fix bro :)

**Comment by kuteteen** [comment]
and share user and pass default login bro :)

**Comment by kuteteen** [comment]
install done! thanks bro!

**Comment by iMokhles** [comment]
default login info is here

[UserFactory.php](https://github.com/iMokhles/IMRepo/blob/master/database/factories/UserFactory.php)

**Comment by kuteteen** [comment]
hi. i add my repo in cydia. but error 404  Not Found. https://url/ ./Packages http 404

**Comment by kuteteen** [comment]
> default login info is here
> 
> [UserFactory.php](https://github.com/iMokhles/IMRepo/blob/master/database/factories/UserFactory.php)

hi. i'm create new package but site dont make ./Packages

**Comment by kuteteen** [comment]
i'm upload repo in share hostting :)

**Comment by iMokhles** [comment]
It's Okey it should work normally with share hosting.

**Comment by kuteteen** [comment]
> It's Okey it should work normally with share hosting.

i'm upload and install repo work but i'm add in cydia app error and repo clear  :( help me fix
![img_6321](https://user-images.githubusercontent.com/16338693/53789065-1dba5980-3f56-11e9-80b2-6c4732d49fe8.PNG)

**Comment by iMokhles** [comment]
send me your skype or instance message identifier by email: mokhleshussien@aol.com to check it with you.

**Comment by iMokhles** [comment]
tried your repo link it say that you didn't generate the encryption key

**Comment by kuteteen** [comment]
> tried your repo link it say that you didn't generate the encryption key

sorry. i reinstall :) Application key set successfully.. pls help me fix error 404.. user and password login default of you :)

**Comment by kuteteen** [comment]
i using skype chat :)
